export * from "./Home";
export * from "./SingleProduct";
export * from "./about";
export * from "./contact";
export * from "./error";
export * from "./login";
export * from "./notFound";
export * from "./register";
export * from "./shop";
